from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, ValidationError, TextAreaField, HiddenField
from wtforms.validators import DataRequired, EqualTo, Length
from wtforms.widgets import TextArea
from flask_ckeditor import CKEditorField
from flask_wtf.file import FileField

class MessagesForm(FlaskForm):
    name = StringField()
    email = StringField()
    company_name = StringField()
    company_size = StringField()
    industry = StringField()
    other_industry = StringField()
    help_with = StringField()
    other_help = StringField()
    submit = SubmitField()

class OTPForm(FlaskForm):
    otp = StringField()
    submit = SubmitField()

class QuestionnaireForm(FlaskForm):
    name = StringField(validators=[DataRequired()])
    email = StringField(validators=[DataRequired()])
    phone = StringField(validators=[DataRequired()])
    company = StringField(validators=[DataRequired()])
    position = StringField(validators=[DataRequired()])
    answerOne = StringField()
    answerTwo = StringField()
    answerThree = StringField()
    answerFour = StringField()
    answerFive = StringField()
    answerSix = StringField()
    answerSeven = StringField()
    answerEight = StringField()
    answerNine = StringField()
    answerTen = StringField()
    answerEleven = StringField()
    answerTwelve = StringField()
    answerThirteen = StringField()
    answerFourteen = StringField()
    answerFifteen = StringField()
    answerSixteen = StringField()
    answerSeventeen = StringField()
    answerEighteen = StringField()
    answerNineteen = StringField()
    answerTwenty = StringField()
    answerTwentyOne = StringField()
    answerTwentyTwo = StringField()
    answerTwentyThree = StringField()
    answerTwentyFour = StringField()
    answerTwentyFive = StringField()
    answerTwentySix = StringField()
    answerTwentySeven = StringField()
    answerTwentyEight = StringField()
    answerTwentyNine = StringField()
    answerThirty = StringField()
    answerThirtyOne = StringField()
    answerThirtyTwo = StringField()
    answerThirtyThree = StringField()
    answerThirtyFour = StringField()
    answerThirtyFive = StringField()
    answerThirtySix = StringField()
    answerThirtySeven = StringField()

    #Added Components
    inputOne = StringField()
    inputTwo = StringField()
    inputThree = StringField()
    inputFour = StringField()
    inputFive = StringField()
    inputSix = StringField()
    inputSeven = StringField()
    inputEight = StringField()
    inputNine = StringField()
    inputTen = StringField()
    inputEleven = StringField()
    inputTwelve = StringField()
    inputThirteen = StringField()
    inputFourteen = StringField()
    inputFifteen = StringField()
    inputSixteen = StringField()
    inputSeventeen = StringField()
    inputEighteen = StringField()
    inputNineteen = StringField()
    inputTwenty = StringField()
    inputTwentyOne = StringField()
    submit = SubmitField()
