name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: 'devtegrate-brand'
  PYTHON_VERSION: '3.9'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install Flask==2.2.5
          export FLASK_DEBUG=True
          export FLASK_APP=app.py

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Flask installation
        run: flask --version

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            .
            venv/
  
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'devtegrate-llc-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3CFB0997113E48F089AA7053CE037FAB }}
